#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @author    Stéphane Bocquet <stephane_bocquet@hotmail.com>
# @copyright Copyright (c) 2012 Marcel Beck
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        echo "Initialize configuration"

        # Check for XML config
        if ! omv_config_exists "/config/services/git"; then
            echo "Initialize Git plugin configuration"
            ENABLE="0"
            SYMLINKS_ENABLE="0"
            MNTENTREF=""
            REALM="Git Repositories on OMV"
            REPOSITORY_ROOT=""
            REPOS=""
            GITWEB_ENABLE="0"
            GITWEB_ANON="0"
            SHOWTAB="0"
        else
            echo "Importing previous configuration"
            ENABLE="$(omv_config_get "/config/services/git/enable")"

            if ! omv_config_exists "/config/services/git/symlinks-enable"; then
                SYMLINKS_ENABLE="0"
            else
                SYMLINKS_ENABLE="$(omv_config_get "/config/services/git/symlinks-enable")"
            fi

            MNTENTREF="$(omv_config_get "/config/services/git/mntentref")"
            REALM="$(omv_config_get "/config/services/git/realm")"
            REPOSITORY_ROOT="$(omv_config_get "/config/services/git/repository-root")"
            REPOS="$(omv_config_get "/config/services/git/repos")"
            GITWEB_ENABLE="$(omv_config_get "/config/services/git/gitweb-enable")"
            GITWEB_ANON="$(omv_config_get "/config/services/git/gitweb-anon")"
            SHOWTAB="$(omv_config_get "/config/services/git/showtab")"
        fi

        omv_config_delete "/config/services/git"

        object="<enable>${ENABLE}</enable>"
        object="${object}<symlinks-enable>${SYMLINKS_ENABLE}</symlinks-enable>"
        object="${object}<mntentref>${MNTENTREF}</mntentref>"
        object="${object}<realm>${REALM}</realm>"
        object="${object}<repository-root>${REPOSITORY_ROOT}</repository-root>"
        object="${object}<repos>${REPOS}</repos>"
        object="${object}<gitweb-enable>${GITWEB_ENABLE}</gitweb-enable>"
        object="${object}<gitweb-anon>${GITWEB_ANON}</gitweb-anon>"
        object="${object}<showtab>${SHOWTAB}</showtab>"
        omv_config_add_element "/config/services" "git" "${object}" true

        chown -R openmediavault:openmediavault /var/www/gitweb

        index=$(omv_config_get_count "//services/git/repos/repo")
        while [ ${index} -gt 0 ]
        do
            reporef=$(omv_config_get "//services/git/repos/repo[position()=${index}]/uuid")

            privileges_index=$(omv_config_get_count "//services/git/repos/repo[uuid='${reporef}']/privileges/privilege")
            while [ ${privileges_index} -gt 0 ]
            do
                USERUUID="$(omv_config_get "//services/git/repos/repo[position()=${index}]/privileges/privilege[position()=${privileges_index}]/userref")"
                if [ "${USERUUID}" != "" ]; then
                    if omv_isuuid "${USERUUID}"; then
                        USERNAME=$(omv_config_get "//system/usermanagement/users/user[uuid='${USERUUID}']/name")
                        if ! omv_config_exists "//services/git/repos/repo[position()=${index}]/privileges/privilege[position()=${privileges_index}]/username"; then
                            echo "Transform User UUID: ${USERUUID} to Username: ${USERNAME}"
                            omv_config_add_element "//services/git/repos/repo[position()=${index}]/privileges/privilege[position()=${privileges_index}]" "username" "${USERNAME}"
                            omv_config_delete "//services/git/repos/repo[position()=${index}]/privileges/privilege[position()=${privileges_index}]/userref"
                        fi
                    fi
                fi

                GROUPUUID="$(omv_config_get "//services/git/repos/repo[position()=${index}]/privileges/privilege[position()=${privileges_index}]/groupref")"
                if [ "${GROUPUUID}" != "" ]; then
                    if omv_isuuid "${GROUPUUID}"; then
                        GROUPNAME=$(omv_config_get "//system/usermanagement/groups/group[uuid='${GROUPUUID}']/name")
                        if ! omv_config_exists "//services/git/repos/repo[position()=${index}]/privileges/privilege[position()=${privileges_index}]/groupname"; then
                            echo "Transform Group UUID: ${GROUPUUID} to Groupname: ${GROUPNAME}"
                            omv_config_add_element "//services/git/repos/repo[position()=${index}]/privileges/privilege[position()=${privileges_index}]" "groupname" "${GROUPNAME}"
                            omv_config_delete "//services/git/repos/repo[position()=${index}]/privileges/privilege[position()=${privileges_index}]/groupref"
                        fi
                    fi
                fi

                privileges_index=$(( ${privileges_index} - 1 ))
            done

            index=$(( ${index} - 1 ))
        done

        # Enable required apache modules
        # echo "Enable apache modules"
        # a2enmod authnz_external dav_svn dav_fs

        # load authz_svn for wheezy only
        # RELEASE=$(lsb_release -cs)
        # if [ "${RELEASE}" = "wheezy" ]; then
        #     a2enmod authz_svn
        # fi

        echo "Clean up old installation"
        # Clean up old installation?
        if [ -f /etc/nginx/openmediavault-webgui.d/git.conf ]; then
            /bin/rm -f /etc/nginx/openmediavault-webgui.d/git.conf
        fi

        echo "Make configuration"
        omv-mkconf git

        echo "Restart nginx"
        monit restart nginx

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
